CollegeInformationSubscription/CollegeInformationSubscription/urls.py
from django.contrib import admin
from django.urls import path, include

from systemadministrator import views
from buysystem import views as bv

urlpatterns = [
    path("",views.ztlogin),
    path('index/', bv.index),
    path("login/", views.administratorLogin,),
    # 注册页面
    path("userregister/", views.userRegistration,),
    path("APP1/", include("systemadministrator.urls")),
    path("APP2/", include("buysystem.urls")),
    path("tc/", views.tuichudengl, name="tc"),

]
handler404 = views.page_not_found
handler500 = views.page_error

CollegeInformationSubscription/buysystem/urls.py
from django.contrib import admin
from django.urls import path

from buysystem import views
# app_name="Administrator"
urlpatterns = [
    path("index/", views.index),
    path("details/", views.details),
    path("addcomment/", views.addcomment),
    path("submitorder/", views.submitorder),
    path("uploaddata/", views.uploaddata),
    path("changepassword/", views.changepassword),
    path("order/", views.order),
    path("savebookid/", views.savebookid),

]

CollegeInformationSubscription/systemadministrator/urls.py
from django.contrib import admin
from django.urls import path

from systemadministrator import views

app_name = "Administrator"
urlpatterns = [
    # 管理员页面
    path("", views.index, name="index"),
    #  用户信息分页路由
    path("studentslist/<int:pall>", views.studentslist, name="studentslist"),
    # 用户信息
    path("studentslist/", views.studentslist, name="studentslist"),
    # 用户删除路由
    path("deletes/<int:id>/", views.delets, name="deletes"),
    # 主信息
    path("home/", views.home, name="home"),
    path("studentsadd/", views.addstudents, name="studentsadd"),
    # 更改学生密码
    path("studentsup/<int:id>", views.updatastudents, name="studentsup"),
    # 添加数据
    path("addbook/", views.addbook, name="addbook"),
    # 书籍列表
    path("booklist/", views.booklist, name="booklist"),
    path("booklist/<int:pall>", views.booklist, name="booklist"),
    # 删除书籍
    path("deletebook/<int:id>/", views.deletbook, name="deletebook"),
    # 修改书籍
    path("updatabook/<int:id>/", views.updatebook, name="updatabook"),
    # 设置公告
    path("act/", views.announcement, name="act"),
    # 查看公告
    path("lookact/", views.lookannouncement, name="lookact"),
    # 添加学校
    path("shooladd/", views.shooladd, name="shooladd"),
    # 学校列表
    path("schoollist/", views.shoollist, name="shoollist"),
    #  删除学校
    path("deleteschool/<int:id>", views.deletschool, name="deletschool"),
    #  修改学校
    path("upschool/<int:id>", views.upschool, name="upschool"),
    #  学生添加
    path("addsut/", views.addstu, name="addsut"),
    # 学生列表
    path("stulist/", views.stulist, name="stulist"),
    # 删除学生
    path("deletstu/<int:id>/", views.deletsut, name="delets"),
    path("upsut/<int:id>/", views.upsut, name="upsut"),
    # 订单列表
    path("Orderslist/", views.order, name="Orderslist"),
    path("saut/", views.saudit, name="saut"),
    path("upsaut/", views.sauditsh, name="upsaut"),
    path("delesaut/", views.deletsaud, name="deletsaud"),
    #图书大图片:
    path("bookimgbig",views.bookbig,name="bookbig"),
    #
    path("comment/",views.comment,name="comment"),
    path("bookor/",views.bookor,name="bookor"),
    path("usercom/",views.useror,name="useror"),
    path("ckzl/",views.ckzl,name="xkzl"),
    path("bjdd",views.classgeade,name="bjdd")
]

CollegeInformationSubscription/systemadministrator/models.py
from datetime import datetime

from django.db import models

# Create your models here.


# 注册表
class Register(models.Model):
    id = models.AutoField(primary_key=True)
    account = models.CharField(max_length=16,unique=True)  # 账号
    name = models.CharField(max_length=16)  # 姓名
    password = models.CharField(max_length=32)  # 密码
    class Meta:
            db_table="Register"

# 学校信息表
class SchoolData(models.Model):

    id = models.AutoField(primary_key=True)
    college = models.CharField(max_length=16)  # 学院
    specialty = models.CharField(max_length=32)  # 专业
    year = models.DateTimeField()  # 入学年份
    grade=models.CharField(max_length=10,default="空")

    class Meta:
            db_table="SchoolData"

# 学生信息表
class StudentData(models.Model):
    id = models.AutoField(primary_key=True)
    studentnumber = models.IntegerField(unique=True)  # 学号 唯一
    studentgender = models.CharField(max_length=2)  # 性别
    studentname = models.CharField(max_length=16)  # 姓名
    stuentjurisdiction = models.IntegerField(default=0)  # 权限 0表示普通学生 1表示班级负责人
    studentschool = models.ForeignKey(to='SchoolData', on_delete=models.DO_NOTHING)  # 学校信息表id
    classgrade = models.CharField(max_length=16,default="空")  # 班级
    class Meta:
            db_table="StudentData"

# 图书表
class Books(models.Model):
    id = models.AutoField(primary_key=True)
    bookname = models.CharField(max_length=32)  # 图书名
    bookimgurl = models.CharField(max_length=150)  # 图书图片url
    bookprice = models.IntegerField()  # 图书价格
    bookbrief=models.TextField(default="空")#图书简介
    bookauthor=models.CharField(max_length=20,default="空")#图书作者
    bookimgbig=models.CharField(max_length=40,default="空")#图书大图片
    class Meta:
        db_table = "Books"


# 订单表
class Orders(models.Model):
    id = models.AutoField(primary_key=True)
    ordernumber = models.CharField(max_length=32)  # 订单号  唯一 日期+随机数
    ordertime = models.DateTimeField()  # 订单时间
    orderprice = models.IntegerField()  # 总价
    orderregister = models.ForeignKey(to='Register', on_delete=models.DO_NOTHING)  # 注册表id
    orderbook = models.ForeignKey(to='Books', on_delete=models.DO_NOTHING)  # 图书表id
    orderstudent = models.ForeignKey(to='StudentData', on_delete=models.DO_NOTHING,related_name="student")  # 学生信息表id
    class Meta:
        db_table = "Orders"

# 资料表
class Datas(models.Model):
    id = models.AutoField(primary_key=True)
    dataname = models.CharField(max_length=32)  # 资料名
    dataimgurl = models.CharField(max_length=64)  # 资料图片url
    dataintroduce = models.CharField(max_length=128)  # 资料简介
    qqnumber = models.IntegerField(default=0)  # QQ号
    dataauthor = models.CharField(max_length=20, default="空")  # 资料作者
    dataregister = models.ForeignKey(to='Register', on_delete=models.DO_NOTHING)  # 注册表id
    datasaudit=models.IntegerField(default=0)
    class Meta:
        db_table = "Datas"

# 评论表
class Comments(models.Model):
    id = models.AutoField(primary_key=True)
    commentstring = models.CharField(max_length=50)  # 评论内容
    commenttime = models.DateTimeField(auto_now_add=datetime.now)
    commentstudent = models.ForeignKey(to='Books', on_delete=models.DO_NOTHING,related_name="books")  # 图书表id
    commentregister = models.ForeignKey(to='Register', on_delete=models.DO_NOTHING)  # 注册表id
    class Meta:
        db_table = "Comments"

# 公告表
class Notices(models.Model):
    id = models.AutoField(primary_key=True)
    noticestring = models.CharField(max_length=50)  # 公告内容
    noticetime = models.DateTimeField(auto_now_add=datetime.now)  # 公告时间
    noticestate = models.IntegerField(default=1)  # 公告状态  0表示历史  1表示最新
    class Meta:
        db_table = "Notices"

CollegeInformationSubscription/systemadministrator/views.py
import json
from datetime import datetime

from django.core.paginator import Paginator
from django.shortcuts import render, HttpResponse, redirect

# Create your views here.
from CollegeInformationSubscription import settings
from CollegeInformationSubscription.settings import STATICFILES_DIRS
from systemadministrator import file_dispose
from systemadministrator.models import Register, Books, Notices, SchoolData, StudentData, Orders, Datas, Comments


# 后台首页
def index(request):
    return render(request, "systemadministrator/admin.html")


def home(request):
    register=Register.objects.count()
    school=SchoolData.objects.count()
    student=StudentData.objects.count()
    gly=StudentData.objects.filter(stuentjurisdiction=1).count()
    books=Books.objects.count()
    datas=Datas.objects.filter(datasaudit=0).count()
    return render(request, "systemadministrator/home.html",locals())


# 用户注册
def userRegistration(request):
    if request.method == "POST":
        users = request.POST.dict()
        error = ""
        user = users["user"]
        password = users["password"]
        passwords = users["passwords"]
        username = users["username"]
        if len(user) == 8:
            if len(password) >= 6:
                if passwords == password:
                    useridct = {'account': user, "name": username, "password": password}
                    print("进来了")
                    try:
                        Register.objects.create(**useridct)
                        return redirect("/login/")
                    except Exception as a:
                        print(a)
                        error = "账号已被注册"
                else:
                    error = "密码输入不正确"
            else:
                error = "密码不能低于6位"
        else:
            error = "请输入8位学号"
        return render(request, "systemadministrator/userRegistration.html", locals())
    return render(request, "systemadministrator/userRegistration.html")


def ztlogin(request):
    return redirect("/login/")


def administratorLogin(request):
    if request.method == "POST":
        users = request.POST.dict()
        user = users["user"]
        password = users["password"]
        useridct = {'account': user, "password": password}
        users = Register.objects.filter(**useridct)
        print("尽量ILE")
        if user == "admin" and password == "root":
            # 设置管理员权限
            request.session["jd"] = 2
            # 设置管理员身份
            request.session["iy"] = "管理员"
            # 设置管理员身份
            request.session["name"] = "root"
            # 设置登录时间.
            request.session["time"] = datetime.now().strftime("%Y-%m-%d %m:%d")
            # 设置管理员id
            request.session["id"] = 11111111
            request.session['bookidstr'] = []
            return redirect("Administrator:index")
        elif users:
            request.session["jd"] = 1
            # 设置学生身份
            request.session["iy"] = "学生"
            # 设置学生身份
            request.session["name"] = users.get().name
            # 设置登录时间.
            request.session["time"] = datetime.now().strftime("%Y-%m-%d %m:%d")
            # 设置学生id
            request.session["id"] = users.get().id
            request.session['bookidstr'] = []
            return redirect("/index/")
        else:
            erro = "账号或密码错误"
            return render(request, "systemadministrator/administratorLogin.html", locals())
    return render(request, "systemadministrator/administratorLogin.html")


# 学生账号列表
def studentslist(request, pall=1):
    register = Register.objects.all()
    piblics = register.values_list()
    paginator = Paginator(piblics, 5)
    num = paginator.num_pages
    try:
        page = paginator.page(pall)
    except:
        if pall == 1:
            page = paginator.page(pall)
        page = paginator.page(pall - 1)

    return render(request, "systemadministrator/Studentsmessage.html", locals())


# 删除学生账号
def delets(request, id):
    try:
        delet = Register.objects.get(pk=id)
        delet.delete()
        return HttpResponse("删除成功")
    except Exception as  e:
        return HttpResponse("删除失败")


# 添加学生
def addstudents(request):
    if request.method == "POST":
        users = request.POST.dict()
        error = ""
        user = users["user"]
        password = users["password"]
        passwords = users["passwords"]
        username = users["username"]
        if len(user) == 8:
            if len(password) >= 6:
                if passwords == password:
                    useridct = {'account': user, "name": username, "password": password}
                    try:
                        Register.objects.create(**useridct)
                        return redirect("Administrator:studentslist")
                    except Exception as a:
                        error = "账号已被注册"
                else:
                    error = "密码输入不正确"
            else:
                error = "密码不能低于6位"
        else:
            error = "请输入8位学号"
        return render(request, "systemadministrator/Studentaddhtml.html", locals())
    return render(request, "systemadministrator/Studentaddhtml.html")


# 修改学生密码
def updatastudents(request, id):
    updata = Register.objects.get(pk=id)
    if request.method == "POST":
        error = ""
        ids = request.POST.get("id")
        user = request.POST.get("user")
        username = request.POST.get("username")
        password = request.POST.get("password")
        passwords = request.POST.get("passwords")
        if len(user) == 8:
            if passwords == password:
                try:
                    Register.objects.filter(id=ids).update(
                        account=user, name=username, password=password)
                    return redirect("Administrator:studentslist")
                except:
                    error = "用户名已存在"
            else:
                error = "密码输入不正确"
        else:
            error = "请输入8位数id"
        return render(request, "systemadministrator/updatastudents.html", locals())
    return render(request, "systemadministrator/updatastudents.html", locals())


def addbook(request):
    fis = ""
    if request.method == "POST":
        er = ""
        try:
            booking = request.FILES.get("bookimgurl")
            file = file_dispose.fileUoload(booking, is_randomnane=True)
            filebook = settings.MEDIA_ROOT[0]
            fis = file.file_judge(filebook)[1]
        except:
            er = "你上传的图片有问题"
        dicts = request.POST.dict()
        dicts["bookimgurl"] = fis
        try:
            Books.objects.create(**dicts)
            return redirect("Administrator:booklist")
        except Exception as  e:
            print(e)
            er = "保存书籍有误"
        return render(request, "systemadministrator/addbook.html", locals())
    return render(request, "systemadministrator/addbook.html")


# 书籍列表
def booklist(request, pall=1):
    book = Books.objects.all()
    piblics = book.values_list()
    paginator = Paginator(piblics, 5)
    try:
        num = paginator.num_pages
        page = paginator.page(pall)
    except:
        if pall == 1:
            page = paginator.page(pall)
        page = paginator.page(pall - 1)
    return render(request, "systemadministrator/booklist.html", locals())


# 删除书籍
def deletbook(request, id):
    try:
        delet = Books.objects.get(pk=id)
        delet.delete()
        return HttpResponse("删除成功")
    except Exception as  e:
        return HttpResponse("不可以删除此书 有关联订单")


# 编辑图书
def updatebook(request, id):
    book = Books.objects.get(pk=id)
    if request.method == "POST":
        ids = request.POST.get("id")
        bookname = request.POST.get("bookname")
        bookprice = request.POST.get("bookprice")
        bookauthor = request.POST.get("bookauthor")
        bookimgurl = request.FILES.get("bookimgurl")
        bookbrief = request.POST.get("bookbrief")
        if bookimgurl == None:
            bookimgurl = book.bookimgurl
        else:
            file = file_dispose.fileUoload(bookimgurl, is_randomnane=True)
            filebook = settings.MEDIA_ROOT[0]
            bookimgurl = file.file_judge(filebook)[1]
        if bookbrief == "":
            bookbrief = book.bookbrief
        Books.objects.filter(id=ids).update(bookname=bookname, bookprice=bookprice, bookauthor=bookauthor,
                                            bookimgurl=bookimgurl, bookbrief=bookbrief)
        return redirect("Administrator:booklist")
    return render(request, "systemadministrator/updatabook.html", locals())


# 公告
def announcement(request):
    data = {"resq": ""}
    if request.method == "POST":
        no = Notices.objects
        try:
            act = request.POST.dict()
            if act != None:
                ms = no.all()
                if ms:
                    ms[0].delete()
            no.create(**act)
            data["resq"] = "设置成功"
        except Exception as  e:
            print(e)
            data["resq"] = "设置失败"
        return HttpResponse(json.dumps(data))
    return render(request, "systemadministrator/setTheAnnouncement.html")


# 查看公告
def lookannouncement(request):
    no = Notices.objects.all()
    return HttpResponse(no[0].noticestring)


# 学校添加
def shooladd(request):
    if request.method == "POST":
        datas = {"resq": ""}
        shool = request.POST.dict()
        s = shool["year"].split("-")[0]
        shool["grade"] = s + "级"
        try:
            SchoolData.objects.create(**shool)
            datas["resq"] = "保存成功"
        except Exception as  E:
            print(E)
            datas["resq"] = "保存失败"
        return HttpResponse(json.dumps(datas))
    return render(request, "systemadministrator/shooladd.html")


def shoollist(request):
    school = SchoolData.objects.all()
    schoollist = school.values_list()
    s = request.GET.get("id", 1)
    pag = Paginator(schoollist, 5, 1)
    try:
        page = pag.page(s)
    except:
        if s == 1:
            page = pag.page(s)

CollegeInformationSubscription/templates/systemadministrator/Studentaddhtml.html
{% extends "systemadministrator/base.html" %}
{% block body %}
    <body class="layui-body-content">
    <div style="width: 100% ; text-align: center">
        <div class="layui-fluid" style="width: 100% ; text-align: center">
            <div class="layui-row layui-col-space15">
                <div class="layui-col-md6">
                    <div class="layui-card">
                        <div class="layui-card-header">学生账号添加</div>
                        <FORM method="post" action="{% url "Administrator:studentsadd" %}">
                            <div class="layui-card-body layui-row layui-col-space10">

                                <div class="layui-col-md6">
                                    <input type="text" name="user" placeholder="请输入8位数学号" autocomplete="off"
                                           class="layui-input">
                                </div>
                                <div class="layui-col-md6">
                                    <input type="text" name="username" placeholder="请输入姓名" autocomplete="off"
                                           class="layui-input">
                                </div>
                                <div class="layui-col-md6">
                                    <input type="password" name="password" placeholder="请输入密码" autocomplete="off"
                                           class="layui-input">
                                </div>
                                <div class="layui-col-md6">
                                    <input type="password" name="passwords" placeholder="请确认密码" autocomplete="off"
                                           class="layui-input">
                                </div>
                            </div>
                                {{ error }}
                            <DIV>
                                    <button class="layui-btn layui-btn-xs">提交</button>
                            </DIV>
                        </FORM>
                    </div>
                </div>
            </div>
    </body>
    </div>
{% endblock %}

CollegeInformationSubscription/templates/systemadministrator/booklist.html
{% extends "systemadministrator/bses.html" %}
{% load static %}
{% block wrapper %}
    <div class="container-fluid">
        <!-- Breadcrumb-->
        <div class="col-sm-3">
            <div class="btn-group float-sm-right">
            </div>
        </div>
    </div>
    <!-- End Breadcrumb-->
    <div class="row">
        <div class="col-lg-11">
            <div class="card">
                <div class="card-header text-uppercase text-primary">书目列表</div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table">
                            <thead class="thead-primary">
                            <tr>
                                <th scope="col">书名</th>
                                <th scope="col">图书作者</th>
                                <th scope="col">图书价格</th>
                                <th scope="col">图书图片</th>
                                <th scope="col">图书简介</th>
                                <th scope="col">设置大图片</th>
                                <th scope="col">删除</th>
                                <th scope="col">编辑</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for foo in page %}
                                <tr>
                                    <td><a href="{% url "Administrator:comment" %}?bookid={{ foo.0 }}">{{ foo.1 }}</a></td>
                                    <td>{{ foo.5 }}</td>
                                    <td>{{ foo.3 }}</td>
                                    <td><img src="{% static 'book' %}/{{ foo.2 }} " width="50" height="50"></td>
                                    <td>
                                        <div style="height: 30px ;width: 30px ">{{ foo.4 }}</div>
                                    </td>
                                    <td>
                                        <div>
                                            <div class="fa-hover col-lg-6 col-xl-4">
                                                <a href="{% url "Administrator:bookbig"%}?id={{ foo.0 }}"><i aria-hidden="true"
                                                                                class="fa fa-cog"></i> <span
                                                        class="sr-only">Example of</span> 设置大图片</a>
                                            </div>
                                        </div>
                                    </td>
                                    <td><a class="show-code dle" href="javascript:;"
                                           title="{% url "Administrator:deletebook"  id=foo.0 %}"><i
                                            class="icon-trash icons"></i><span
                                            class="name">删除</span> <code class="code-preview" style="display: none;">.icon-trash</code></a>
                                    </td>
                                    <td><a class="show-code" href="{% url  "Administrator:updatabook"  id=foo.0 %}"
                                           title="click to show css class name"><i class="icon-pencil icons"></i><span
                                            class="name">编辑</span> <code class="code-preview" style="display: none;">.icon-pencil</code></a>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="col-sm-12 col-md-7">
                    <div class="dataTables_paginate paging_simple_numbers"
                         id="default-datatable_paginate">
                        <ul class="pagination">


                            {% if page.has_previous %}
                                <li class="paginate_button page-item previous "
                                    id="default-datatable_previous">
                                    <a href="{% url "Administrator:booklist"  pall=page.previous_page_number %}"
                                       aria-controls="default-datatable"
                                       data-dt-idx="0" tabindex="0"
                                       class="page-link">Previous</a></li>


                            {% else %}
                                <li class="paginate_button page-item previous disabled"
                                    id="default-datatable_previous">
                                    <a href=""
                                       aria-controls="default-datatable"
                                       data-dt-idx="0" tabindex="0"
                                       class="page-link">Previous</a>
                                </li>
                            {% endif %}



                            {% for foo in page.paginator.page_range %}
                                <li class="paginate_button page-item active"><a
                                        href="{% url "Administrator:booklist"  pall=foo %}"
                                        aria-controls="default-datatable"
                                        data-dt-idx="1"
                                        tabindex="0"
                                        class="page-link">{{ foo }}</a>
                                </li>
                            {% endfor %}

                            {% if page.has_next %}
                                <li class="paginate_button page-item next"
                                    id="default-datatable_next"><a
                                        href="{% url "Administrator:booklist"  pall=page.next_page_number %}"
                                        aria-controls="default-datatable"
                                        data-dt-idx="7" tabindex="0"
                                        class="page-link">Next</a></li>
                            {% else %}
                                <li class="paginate_button page-item next disabled"
                                    id="default-datatable_next"><a href="#"
                                                                   aria-controls="default-datatable"
                                                                   data-dt-idx="7" tabindex="0"
                                                                   class="page-link">Next</a></li>
                            {% endif %}


                        </ul>
                    </div>
                </div>

            </div>
        </div>
    </div><!--End Row-->
{% endblock %}

CollegeInformationSubscription/templates/systemadministrator/imgck.html
{% extends "systemadministrator/bses.html" %}
{% load static %}
{% block wrapper %}
<div class="row">
        <div class="col-lg-6">
          <div id="accordion4">
              <button type="button"  title="{% url "Administrator:saut" %}" class="btn btn-outline-dark btn-round waves-effect waves-light m-1" id="ak">返回</button>
              <div class="card mb-2">
                <div id="collapse-10" class="collapse show" data-parent="#accordion4">
                  <div class="card-body">
                    <img src="{% static  "book" %}/{{ data.dataimgurl }}" class="img-fluid rounded shadow mb-3" alt="card img">
                    <div class="card-title text-uppercase text-secondary">资料简介</div>
                        {{ data.dataintroduce }}
                  </div>
                </div>
              </div>
            </div>
        </div>

      </div>
{% endblock %} }
{% block scs %}
               var buttons=document.getElementById("ak")
                buttons.onclick=function () {
                        s=buttons.attributes["title"].nodeValue
                        window.location.href=s

                }

{% endblock %}

CollegeInformationSubscription/templates/systemadministrator/setTheAnnouncement.html
{% extends  "systemadministrator/base.html" %}
{% block title %}设置公告{% endblock %}
{% block body %}


    <body>
    <div class="layui-col-md6">
        <div class="layui-card">
            <div class="layui-card-body layui-row layui-col-space10">
                <div class="layui-col-md12">
                    <textarea  id="textact" name="" placeholder="请输入" maxlength="50" class="layui-textarea" required> </textarea>
                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-input-block">
                <button class="layui-btn" id="button" lay-submit="" lay-filter="component-form-element">立即提交</button>
            </div>
        </div>
    </div>
    </body>
{% endblock %}
{% block script %}
    <script>
    $(function () {

           $("#button").click(function () {
                    text=$("#textact").val()
                    console.log(text)
                    if (text!==" "&&text.length<=50){
                             $.ajax({
                            url:"{% url "Administrator:act" %}",
                            data:{noticestring:text},
                            type:"POST",
                            datatype:"json",
                            success:function (data) {
                                    console.log("进来了")
                                    resq=$.parseJSON(data)["resq"]
                                    alert(resq)
                                    window.location.reload()
                            },
                            timeout:4000,
                            error:function (data) {
                                    console.log("出错了")
                            }

                    })
                    }else {
                        alert("请输入公告(50字)")
                    }


           })
    })
    </script>
{% endblock %}