djangoProject15/APP1/urls.py
from django.contrib import admin
from django.urls import path
from  . import views
from  .  import viewstwo,vivethree
app_name="APP1"
urlpatterns = [
        path("addbook/",views.book.as_view(),name="addbook"),
        path("listbook/", views.listbook.as_view(), name="listbook"),
        path("listbook/<int:fall>", views.listbook.as_view(), name="listbook"),
        path("dlebook/<int:pull>", views.dlebook.as_view(), name="dle"),
        path("upbook/<int:pall>",views.upbook.as_view(),name="upbook"),
        path("buybook/", viewstwo.buy_books.as_view(), name="butybook"),
        path("buybooklist/", viewstwo.listbuybook.as_view(), name="butybooklist"),
        path("buybooklist/<int:fall>", viewstwo.listbuybook.as_view(), name="butybooklist"),
        path("sheet/", viewstwo.listsheet.as_view(), name="listsheet"),
        path("sheet/<str:pall>", viewstwo.listsheet.as_view(), name="listsheet"),
        path("sheet/<str:pall>/<int:fall>",viewstwo.listsheet.as_view(),name="listsheet"),
        path("registre/",vivethree.register.as_view(),name="registre"),
        path("login/", vivethree.login.as_view(), name="login"),
        path("logout/",vivethree.exits.as_view(),name="exit")

]

djangoProject15/APP2/urls.py
from django.contrib import admin
from django.urls import path,include
from  . import  views
app_name="APP2"
urlpatterns = [
                path("info/",views.BOOKINFO.as_view(),name="bookinfok"),
                path("info/<int:bid>/", views.BOOKINFO.as_view(), name="bookinfok"),
                path("addbooks/",views.addbooks.as_view(),name="addbooks")
]

djangoProject15/djangoProject15/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    # path('admin/', admin.site.urls),
    path("",include("APP1.urls")),
    path("APP2/",include("APP2.urls"))
]

djangoProject15/APP1/models.py
from datetime import datetime

from django.db import models

# Create your models here.
class Book(models.Model):
    id = models.AutoField(primary_key=True)
    bookname = models.CharField(max_length=20,unique=True)
    bookauthor=models.CharField(max_length=10,default="空")
    bookprice = models.FloatField(default=20.00)
    bookpublic = models.CharField(max_length=20)
    bookaddtime = models.DateTimeField(auto_now_add=datetime.now)

    class Meta:
        db_table = "Book"




class user(models.Model):
    di = models.AutoField(primary_key=True)
    username=models.CharField(max_length=20,unique=True)
    password=models.CharField(max_length=100)
    phone=models.CharField(unique=True,max_length=11)
    email=models.CharField( max_length=20,unique=True,null=True)
    age=models.IntegerField(null=True)
    sex =models.CharField( max_length=2,null=True)
    time=models.DateTimeField(auto_now_add=datetime.now)
    login_type = ((1, '允许登录'), (2, '禁⽌登录'))  # ⽤户⾃定义类型对应
    allowed = models.IntegerField(default=1, choices=login_type)
    name=models.CharField(max_length=20,default="空")
    class Meta:
        db_table="user"

class Bookfigure(models.Model):
    di = models.AutoField(primary_key=True)
    user=models.ForeignKey(user,models.CASCADE, related_name="user" , null=False,default=0)
    book = models.ForeignKey(Book, models.CASCADE, related_name="book",null=False,default=0)
    class Meta:
        db_table = "Bookfigure"

djangoProject15/APP1/views.py
from django.shortcuts import render,HttpResponse,redirect
from django.views.generic import View,ListView
# Create your views here.
from  .models import Book
class book(View):
        def get(self,request):
            return  render(request,"edit_book.html")
        def post(self, request):
            try:
                books=request.POST.dict()
                books.pop("csrfmiddlewaretoken")
                Book.objects.create(**books)
                return redirect("APP1:listbook")
            except Exception :
                dicts="请重新添加书籍"
                return render(request, "edit_book.html",locals())

class listbook(ListView):
            template_name = "book_list.html"
            paginate_by = 4
            # paginate_orphans = 1
            context_object_name = "books"
            page_kwarg = "fall"
            model =  Book
class dlebook(View):
    def get(self,request,pull):
        books=Book.objects.get(pk=pull)
        books.delete()
        return  redirect("APP1:listbook")

class  upbook(View):
        def get(self,request,pall):
            if pall != None :
                try:
                    books=Book.objects.get(pk=pall)
                    return render(request,"add_book.html",locals())
                except Exception :
                    tite ="获取的书籍不存在"
                    return  render(request,"add_book.html",locals())
            else:
                 return  redirect("APP1:listbook")
        def post(self,request,pall):
                try:
                        books=request.POST.dict()
                        books.pop("csrfmiddlewaretoken")
                        lens=len(list(books.values()))
                        if lens==5:
                            Book.objects.filter(pk=books["id"]).update(bookname=books["bookname"],
                            bookauthor=books["bookauthor"], bookprice=books["bookprice"],bookpublic=books["bookpublic"])
                            return redirect("APP1:listbook")
                        else:
                            tite = "不能为空"
                            return redirect("APP1:upbook", locals())

                except Exception :
                        tite="填写有误请重新填写"
                        return  redirect("APP1:upbook",locals())

djangoProject15/APP2/views.py
from django.shortcuts import render
from django.views import View
from rest_framework import serializers, response
# Create your views here.

from  rest_framework.generics import  GenericAPIView
from rest_framework.response import Response
from rest_framework.views import APIView

from APP1.models import Book
from APP2.serializerss import Bookserializers


class   BOOKINFO(GenericAPIView):
            queryset =Book.objects.all()
            def get(self,request,bid=-1):
                print(bid)
                if   bid<0:
                    return  self.find_many(request)
                else:
                    return  self.find_one(request,bid)


            def find_many(self,request):
                bs=Bookserializers(instance=self.queryset.all(),many=True)
                print(bs.data)
                return  Response(data=bs.data)

            def find_one(self,request,bid):
                book=self.queryset.get(id=bid)
                bs=Bookserializers(instance=book)
                print(bs.data)
                return  Response(data=bs.data)


class addbooks(APIView):
    # queryset = Book.objects.all()
    serializer_class=Bookserializers
    def  post(self,request):
        print("aa")
        print(request.POST.dict())
        bs=Bookserializers(data=request.data)
        if bs.is_valid():
             print(bs.validated_data)
             bs.save()
             return Response({"code": 1,"mgs":"添加成功"})
        else:
             print(bs.errors)
             return Response({"code": 0,"msg":bs.errors})

djangoProject15/templates/add_author.html
{% extends "base.html" %}


{% block nav %}
    <li ><a href="/app01/publisher_list/">出版社列表页</a></li>
    <li><a href="/app01/book_list/">图书列表页</a></li>
    <li class="active"><a href="/app01/author_list/">作者列表</a></li>
{% endblock %}

{% block bar %}
    <div class="col-md-9" style=  "justify-content: flex-end;">
            <h1 class="page-header">购买页面</h1>
    <div class="panel panel-primary">
                <!-- Default panel contents -->
        <div class="panel-heading">购买书籍<i class="fa fa-thumb-tack pull-right"></i></div>
            <div class="panel-body">
                <div class="row" style="margin-bottom: 15px">
                    <div class="col-md-4">
                            <div class="input-group">
                                <form action="{% url "APP1:butybook" %}" method="post" name="akan">
                                {% csrf_token %}
                                    <p><select  name="book_id">
                                        <option >选择购买的书籍</option>
                                        {% for book in books %}
                                         <option  value="{{book.id}}">{{book.bookname}}</option>
                                        {% endfor %}

                                    </select></p>
                                    <p><input type="submit" value="提交" ></p>
                                </form>
                            </div><!-
                        </div><!- /input-group -->
                        </div><!-- /.col-md-4 -->
                </div>
     </div>

{% endblock %}

{% block main %}
  
{% endblock %}

djangoProject15/templates/add_book.html
{% extends "base.html" %}



{% block nav %}
    <li ><a href="/app01/publisher_list/">出版社列表页</a></li>
    <li><a href="/app01/book_list/">图书列表页</a></li>
    <li class="active"><a href="/app01/author_list/">作者列表</a></li>
{% endblock %}

{% block bar %}
    <div class="col-md-9" style=  "justify-content: flex-end;">
            <h1 class="page-header">图书管理页面</h1>
        <div class="panel panel-primary">
                <!-- Default panel contents -->
        <div class="panel-heading">修改图书<i class="fa fa-thumb-tack pull-right"></i></div>
            <div class="col-md-2 pull-right">
                            <a class="btn btn-success" href="{% url "APP1:listbook" %}">查看图书列表</a>
                        </div>
            <div  class="panel-body">
                 <form action="#"  method="post">
                     {% csrf_token %}
                    <p>图书名称:<input  type="text" name="bookname" value="{{ books.bookname }}" ></p>
                    <p>作者:<input  type="text"  name="bookauthor" value="{{ books.bookauthor }}"></p>
                    <p>价格:<input type="text" name="bookprice" value="{{ books.bookprice }}"></p>
                    <p>出版社:<input type="text" name="bookpublic" value="{{ books.bookpublic }}"></p>
                     <p><input type="hidden" name="id" value="{{ books.id }}"></p>
                    <p><input type="submit" value="提交" ></p>
                     <p>{{ tite }}</p>
                </form>
            </div>
      </div>
{% endblock %}


{% block main %}



{% endblock %}

djangoProject15/templates/add_publisher.html
{% extends "base.html" %}


{% block nav %}
    <li ><a href="/app01/publisher_list/">出版社列表页</a></li>
    <li><a href="/app01/book_list/">图书列表页</a></li>
    <li class="active"><a href="/app01/author_list/">作者列表</a></li>
{% endblock %}


{% block bar %}
      <div class="col-md-9" style=  "justify-content: flex-end;">
            <h1 class="page-header">出版社管理页面</h1>
        <div class="panel panel-primary">
                <!-- Default panel contents -->
        <div class="panel-heading">添加出版社<i class="fa fa-thumb-tack pull-right"></i></div>
            <div  class="panel-body">
                         <form action="{% url  "APP1:addpublic" %} "  method="post">
                                        <p>出版社名称:<input type="text" name="publicname"></p>
                                        <p>出版社地址:<input type="text" name="publicsite"></p>
                                        <p><input type="submit" value="提交" ></p>
                                    </form>
            </div>
      </div>
{% endblock %}



{% block main %}
 
 
 

{% endblock %}

djangoProject15/templates/author_list.html
{% extends "base.html" %}



{% block nav %}
    <li ><a href="#">出版社列表页</a></li>
    <li><a href="#">图书列表页</a></li>
    <li class="active"><a href="#">作者列表</a></li>
{% endblock %}

{% block bar %}
     <div class="col-md-9" style=  "justify-content: flex-end;">
            <h1 class="page-header">{% block title %}卖家消费清单{% endblock %}</h1>
            <div class="panel panel-primary">
                <!-- Default panel contents -->
                <div class="panel-heading">消费清单 <i class="fa fa-thumb-tack pull-right"></i></div>
                <div class="panel-body">
                <div class="row" style="    margin-bottom: 15px">
                        <div class="col-md-4">
                            <div class="input-group">
                                <input type="text" class="form-control" placeholder="Search for...">
                                <span class="input-group-btn">
                                    <button class="btn btn-default" type="button">搜索</button>
                                </span>
                            </div><!-- /input-group -->
                        </div><!-- /.col-md-4 -->
                        <div class="col-md-2 pull-right">
                            <a class="btn btn-success" href="{% url "APP1:butybook" %}">购买书籍</a>
                        </div>
                </div>
                      <div>
                          <table class="table table-dark">
                              <thead>
                                <tr>
                                    {% block bt %}
                                    <th scope="col">序号</th>
                                    <th scope="col">卖家</th>
                                    <th scope="col">图书</th>
                                    <th scope="col">价格</th>
                                        {% endblock %}
                                </tr>
                              </thead>
                              <tbody>
                              {% block bs %}
                                  {% for foo  in books%}
                                             <tr>
                                                 <th scope="row">{{ foo.di }}</th>
                                                 <td><a href="{%url "APP1:listsheet"  pall=foo.user.di%}">{{ foo.user.name }}</a></td>
                                                <td><a>{{ foo.book.bookname }}</a></td>
                                                <td>{{ foo.book.bookprice }}</td>
                                            </tr>
                                  {% endfor %}
                                 {% endblock %}
                              </tbody>
                            </table>
                      </div>
                </div>
    {% endblock %}
{% block pages %}
     {% for book in paginator.page_range %}
           <a href="{% url "APP1:butybooklist" fall=book %}"> {{book}}</a>
     {% endfor %}
{% endblock %}
{% block sa %}
    {% if paginator.num_pages < 1 %}
             {% url "APP1:butybooklist" fall=page_obj.previous_page_number %}
    {% elif page_obj.has_other_pages%}
           {% url "APP1:butybooklist" fall=1 %}
        {% endif %}
{% endblock %}
{% block la%}
     {% if page_obj.has_next%}
         {%  url "APP1:butybooklist" fall=page_obj.next_page_number %}
       {% else %}
               {% url "APP1:butybooklist" fall=1 %}
        {% endif %}
{% endblock %}

{% block main %}
   <!--这是表格-->
  

{% endblock %}

djangoProject15/templates/base.html
<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <title>图书管理系统</title>

    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- HTML5 shim 和 Respond.js 是为了让 IE8 支持 HTML5 元素和媒体查询（media queries）功能 -->
    <!-- 警告：通过 file:// 协议（就是直接将 html 页面拖拽到浏览器中）访问页面时 Respond.js 不起作用 -->
    <!--[if lt IE 9]>
     <script src="https://cdn.jsdelivr.net/npm/html5shiv@3.7.3/dist/html5shiv.min.js"></script>
      <script src="https://cdn.jsdelivr.net/npm/respond.js@1.4.2/dest/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
   <!--分页名称-->
    <h1 class="text-center">图书管理系统</h1>
    <!--这是导航栏-->
    {% include "nav.html" %}
   <!--这是侧栏-->
   <div class="container-fluid">
        <div class="row">
        <div class="col-md-3">
            <ul class="nav nav-sidebar">
                {% block nav %}

                {% endblock %}
            </ul>
        </div>
  <!--标题栏-->
 {% block bar %}

 {% endblock %}
 <!--主程序-->
{% block main%}

{% endblock %}

  <!--这是页码-->
{% block my %}
    <nav aria-label="Page navigation">
  <ul class="pagination">
    <li>
              <a href="{% block sa %}
                {% endblock %}">
                            &laquo;
              </a>
    </li>


    <li>{% block  pages %}
<a href="#">1</a> {% endblock  %}
</li>
      <li>
      <a href="{% block la %}
        {% endblock %}" aria-label="Previous">
        <span aria-hidden="true">&raquo;</span>
      </a>
    </li>
  </ul>
</nav>
{% endblock %}
            <script>
                {% block script %}

                {% endblock %}
            </script>
  </body>
</html>

djangoProject15/templates/book_list.html
{% extends "base.html" %}



{% block nav %}
    <li ><a href="#">出版社列表页</a></li>
    <li><a href="#">图书列表页</a></li>
    <li class="active"><a href="#">作者列表</a></li>
{% endblock %}

{% block bar %}
     <div class="col-md-9" style=  "justify-content: flex-end;">
            <h1 class="page-header">图书管理页面</h1>
            <div class="panel panel-primary">
                <!-- Default panel contents -->
                <div class="panel-heading">图书列表 <i class="fa fa-thumb-tack pull-right"></i></div>
                <div class="panel-body">
                    <div class="row" style="margin-bottom: 15px">
                        <div class="col-md-4">
                            <div class="input-group">
                                <input type="text" class="form-control" placeholder="Search for...">
                                <span class="input-group-btn">
                                    <button class="btn btn-default" type="button">搜索</button>
                                </span>
                            </div><!-- /input-group -->
                        </div><!-- /.col-md-4 -->
                        <div class="col-md-2 pull-right">
                            <a class="btn btn-success" href="{% url "APP1:addbook" %}">新增图书</a>
                        </div>
                           <div>
                          <table class="table table-dark">
                              <thead>
                                <tr>
                                    <th scope="col">序号</th>
                                    <th scope="col">图书名</th>
                                    <th scope="col">作者</th>
                                    <th scope="col">价格</th>
                                    <th scope="col">出版社</th>
                                    <th scope="col">图书添加时间</th>
                                    <th scope="col">操作</th>
                                </tr>
                              </thead>
                              <tbody>
                                  {% for foo  in  books%}
                                             <tr>
                                                 <th scope="row">{{ foo.id }}</th>
                                                <td>{{ foo.bookname }}</td>
                                                <td>{{ foo.bookauthor }}</td>
                                                 <td>{{ foo.bookprice }}</td>
                                                <td>{{ foo.bookpublic }}</td>
                                                 <td>{{ foo.bookaddtime }}</td>
                                                 <td><a href="{% url "APP1:dle" pull=foo.id %}">删除</a><a href="{% url "APP1:upbook" pall=foo.id %}">修改</a></td>
                                            </tr>
                                  {% endfor %}
                              </tbody>
                            </table>
                      </div>
                </div>
                </div>
    {% endblock %}

{##}
{% block pages %}
     {% for book in paginator.page_range %}
           <a href="{% url "APP1:listbook" fall=book %}"> {{book}}</a>
     {% endfor %}
{% endblock %}

{% block sa %}
    {% if paginator.num_pages < 1 %}
             {% url "APP1:listbook" fall=page_obj.previous_page_number %}
    {% elif page_obj.has_other_pages%}
           {% url "APP1:listbook" fall=1 %}
        {% endif %}
{% endblock %}
{% block la%}
     {% if page_obj.has_next%}
         {%  url "APP1:listbook" fall=page_obj.next_page_number %}
       {% else %}
               {% url "APP1:listbook" fall=1 %}
        {% endif %}
{% endblock %}
{#{% block script %}#}
{#        <script src="https://cdn.bootcdn.net/ajax/libs/jquery/3.5.1/jquery.js"></script>#}
{#        <script>#}
{#        $.ajax({#}
{#            type:"put",#}
{#            url:"{% url " a"%}"#}
{#        })#}
{#        </script>#}
{#{% endblock %}#}
{% block main %}
<!--这是表格-->

{% endblock %}

djangoProject15/templates/consumption_list.html
{% extends "author_list.html" %}

{% block title %}
    {{ title }}的书架
{% endblock %}
{% block bt %}
            <th scope="col">序号</th>
            <th scope="col">图书</th>
            <th scope="col">价格</th>
{% endblock %}


{% block bs %}
            {% for foo in item.object_list %}
                    <tr>
                         <th scope="row">{{ foo.di }}</th>
                        <td>{{ foo.book.bookname }}</td>
                        <td>{{ foo.book.bookprice }}</td>
                    </tr>
            {% endfor %}
{% endblock %}
{% block pages %}
     {% for book in  item.paginator.page_range %}
           <a href="{% url "APP1:listsheet" pall=pages fall=book   %}"> {{book}}</a>
     {% endfor %}
{% endblock %}

{% block sa %}

    {% if paginator.num_pages < 1 %}
             {% url "APP1:listsheet" pall=pages  fall=item.previous_page_number %}
    {% elif page_obj.has_other_pages%}
           {% url "APP1:listsheet"  pall=pages   fall=2 %}
        {% endif %}
{% endblock %}
{% block la%}
     {% if page_obj.has_next%}
         {%  url "APP1:listsheet"  pall=pages  fall=item.next_page_number %}
       {% else %}
               {% url "APP1:listsheet" pall=pages    fall=1 %}
        {% endif %}
{% endblock %}
{% block main %}
   <!--这是表格-->


{% endblock %}

djangoProject15/templates/edit_author.html
{% extends "base.html" %}


{% block nav %}
    <li><a href="/app01/publisher_list/">出版社列表页</a></li>
    <li><a href="/app01/book_list/">图书列表页</a></li>
    <li class="active"><a href="/app01/author_list/">作者列表</a></li>
{% endblock %}
{#已使用#}
{% block bar %}
    <div class="col-md-9" style="justify-content: flex-end;">
    <h1 class="page-header">作者管理页面</h1>
    <div class="panel panel-primary">
        <!-- Default panel contents -->
        <div class="panel-heading">编辑作者<i class="fa fa-thumb-tack pull-right"></i></div>
        <div class="panel-body">
            <div class="row" style="margin-bottom: 15px">
                <div class="col-md-4">
                    <div class="input-group">
                    <form  action="{% url "APP1:editauthor" %} " method="post">
                        <p>作者:<input type="text" name="author" value="{{ listboor.author }}"></p>
                        <p>书名:<input  type="text" name="book_sj" value="{{ listboor.book }}"></p>
                        <p><input  type="hidden" name="id" value="{{ listboor.id }}"></p>
                        <p><input type="submit" value="提交"></p>
                    </form>
                    </div>
                    <!-
                </div>
                <!- /input-group -->
            </div><!-- /.col-md-4 -->
        </div>
    </div>
{% endblock %}


{% block main %}

    
	
{% endblock %}

djangoProject15/templates/edit_book.html
{% extends "base.html" %}


{% block nav %}
    <li ><a href="#">出版社列表页</a></li>
    <li><a href="#">图书列表页</a></li>
    <li class="active"><a href="#">作者列表</a></li>
{% endblock %}
{#已使用#}
{% block bar %}
     <div class="col-md-9" style=  "justify-content: flex-end;">
            <h1 class="page-header">图书管理页面</h1>
        <div class="panel panel-primary">
                <!-- Default panel contents -->
        <div class="panel-heading">添加图书<i class="fa fa-thumb-tack pull-right"></i></div>
            <div class="panel-body">
                  <div class="col-md-2 pull-right">
                            <a class="btn btn-success" href="{% url "APP1:listbook" %}">查看图书列表</a>
                        </div>
                <div class="row" style="margin-bottom: 15px">
                    <div class="col-md-4">
                                    <form action="{% url "APP1:addbook" %} "  method="post">
                                        {% csrf_token %}
                                        <p>图书名称:<input  type="text" name="bookname"></p>
                                        <p>作者:<input  type="text"  name="bookauthor"></p>
                                        <p>价格:<input type="text" name="bookprice"></p>
                                        <p>出版社:<input type="text" name="bookpublic"></p>
                                        <p><input type="submit" value="提交" ></p>
                                        <p>{{dicts}}</p>
                                    </form>
                                </div><!-
                        </div><!- /input-group -->
                        </div><!-- /.col-md-4 -->
                </div>
                </div>
{% endblock %}


{% block main %}
 

{% endblock %}

djangoProject15/templates/edit_publisher.html
{% extends "base.html" %}


{% block nav %}
    <li ><a href="/app01/publisher_list/">出版社列表页</a></li>
    <li><a href="/app01/book_list/">图书列表页</a></li>
    <li class="active"><a href="/app01/author_list/">作者列表</a></li>
{% endblock %}

{#已使用#}
{% block bar %}
     <div class="col-md-9" style=  "justify-content: flex-end;">
            <h1 class="page-header">出版社管理页面</h1>
        <div class="panel panel-primary">
                <!-- Default panel contents -->
        <div class="panel-heading">修改出版社<i class="fa fa-thumb-tack pull-right"></i></div>
            <div class="panel-body">
                <div class="row" style="margin-bottom: 15px">
                    <div class="col-md-4">
                            <div class="input-group">
                            </div>
                            <form  action="/APP1/bookpublic/"   method="post">
                                <p>修改出版社<input type="text" name="publicamend" value="{{publiclist.publicname }}"></p>
                                <p>修改出版社地址<input type="text" name="publicsizt" value="{{publiclist.publicsite}}" ></p>
                                <p><input type="hidden" name="id" value="{{publiclist.id }}"></p>
                                <p><input type="submit"></p>
                            </form>
                        </div><!- /input-group -->
                        </div><!-- /.col-md-4 -->
                </div>
                </div>
{% endblock %}



{% block main %}
   <!--这是表格-->
 

{% endblock %}

djangoProject15/templates/jinjafor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{#{% for rego in  %}#}
{##}
{#{% endfor %}#}
<form action=""  method="get">
    <input type="text" name="ll">
    <input type="submit" value="提交">
</form>
<a>lalal</a>
</body>
</html>

djangoProject15/templates/nav.html
 <nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/app01/book_list/">首页</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="{% url  "APP1:listbook" %}">图书列表<span class="sr-only">(current)</span></a></li>
        <li class="active"><a href="{% url  "APP1:butybook" %}">购买书籍</a></li>
      <li class="active"><a href="{% url "APP1:listsheet" %}">出版社列表</a></li>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="#" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url "APP1:registre" %}">注册</a></li>
        <li class="退出">
          <a href="{% url "APP1:exit" %}" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

djangoProject15/templates/register.html
{% extends "base.html" %}





{% block my %}
    <form  ACTION="{% url "APP1:registre" %}"  METHOD="post">
        {% csrf_token %}
        <br><br><br><br>
        <p>账号:<input type="text" name="username" placeholder="请输入账号" required="required"></p>
        <p>密码:<input type="password" name="password" placeholder="请输入密码" required="required"></p>
        <p>确认密码:<input type="password" name="passwords" placeholder="请确认密码" required="required"></p>
        <p> 手机号码:<input type="number" name="phone" placeholder="请输入手机号码" required="required"></p>
        <p>姓名:<input type="text" name="name" placeholder="请输入用户姓名" required="required"></p>
        <p><input type="hidden"  name="allowed" value=1></p>
        <p><input type="submit"></p>
    </form>
    <p>{{ex}}</p>
{% endblock %}